Refactor tests to Pest
spatie/pdf-to-text pull request #57
Opened 2022-11-07 14:03 UTC by alexmanase

2022-11-07 14:28 UTC, freekmurze commented
Seems like the tests are failing, could you take a look?

2022-11-08 09:30 UTC, alexmanase commented
I'll look into it.

2022-11-08 10:21 UTC, freekmurze requested changes

2022-11-08 10:21 UTC, freekmurze commented on tests/PdfToTextTest.php
> +    if (PHP_OS === 'Linux') {
I don't like `else` statements. Could you refactor this to a ternary?

2022-11-09 07:16 UTC, merged

2022-11-09 07:16 UTC, freekmurze commented
Thanks!